EXPERIMENT:
  NAME: ""
  TAG: "dkd_sfkd,vgg13,vgg8,1"
  PROJECT: "cifar100_sfkd"
DISTILLER:
  TYPE: "DKD_SFKD"
  TEACHER: "vgg13"
  STUDENT: "vgg8"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
DKD:
  BETA: 8.0
  ALPHA: 1.0
  T: 4.0
  CE_WEIGHT: 1.0
  WARMUP: 20
  TOPK_PERCENT: 0.7
